### ISSUE TITLE
无法使用NDK构建

### ISSUE THREAD

**Issue by ufo147525** [JackZeng0208/llama.cpp-android-tutorial#1]
无法使用您的方法用安卓ndk构建，提示是这样的
![Screenshot_2024-01-26-18-07-33-91_84d3000e3f4017145260f7618db1d683](https://github.com/JackZeng0208/llama.cpp-android-tutorial/assets/124890662/3611bde8-49f7-4b45-8a4b-3dc6b42149b0)
请问一下ndk的path该如何正确添加呢？

**Comment by JackZeng0208** [comment]
你有运行这一步吗：
```
unzip YOUR_ANDROID_NDK_ZIP_FILE
export NDK=~/path/to/your/unzip/directory
```

**Comment by JackZeng0208** [comment]
然后我看你下的是Termux NDK的最新版（也就是r26），这个版本我不是很确定能不能用
```
cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
```
这个DANDROID_PLATFORM=android-23应该要改成android-26
不过不好意思，我现在也暂时没办法测试这个。我的旧安卓手机才卖掉，新手机还没到货。

**Comment by JackZeng0208** [comment]
https://github.com/ggerganov/llama.cpp?tab=readme-ov-file
然后我的有一部分教程是参考官方的，如果没有解决的话也可以直接问问官方

**Comment by ufo147525** [comment]
谢谢，搞不定了，直接cmake . 
make就能用
