### ISSUE TITLE
你好，基于方法二是将模型部署到gpu上运行吗

### ISSUE THREAD

**Issue by AreckOVO** [JackZeng0208/llama.cpp-android-tutorial#2]
在执行export那个指令后，会出现很多软连接的问题。其次是编译了main文件后再检测gpu吗？不应该先检测再编译生成吗？

**Comment by JackZeng0208** [comment]
你好，我有好久都没有接触过这个项目了。具体我还得重新试一下

**Comment by JackZeng0208** [comment]
然后有关你的第二个问题，opencl是默认支持高通GPU的。只是需要修稿环境变量让termux使用GPU
