### ISSUE TITLE
cmake .. -DLLAMA_CLBLAST=ON 报错

### ISSUE THREAD

**Issue by lumiamilk** [JackZeng0208/llama.cpp-android-tutorial#3]
termux 版本0.119.0-beta.1
版本CLBlast version 1.6.3
vivo IQOO z8 天玑8200

根据Based on OpenCL + CLBlast（Recommend）步骤执行命令，
当执行 cmake .. -DLLAMA_CLBLAST=ON 后出现：
CMake Warning:
Manually-specified variables were not used by the project:

LLAMA_CLBLAST
如果无视这个报错，继续执行cmake --build . --config Release
那么clinfo -l命令没有反应。
识别不到GPU

**Comment by JackZeng0208** [comment]
天玑芯片目前应该是不支持的

**Comment by JackZeng0208** [comment]
我这里也没有天玑芯片的手机，没办法做具体的测试

**Comment by lumiamilk** [comment]
> 我这里也没有天玑芯片的手机，没办法做具体的测试

我又搜了一下，发现
https://github.com/ggerganov/llama.cpp/pull/7735
和
https://github.com/ggerganov/llama.cpp/pull/8139
发现
“devops : remove clblast + LLAMA_CUDA -> GGML_CUDA #8139”
和
“ggml : remove OpenCL #7735”
我一直git clone最新版的😵

**Comment by JackZeng0208** [comment]
明白了，我之后抽空重写一下这个教程
