### ISSUE TITLE
找不到./main文件

### ISSUE THREAD

**Issue by ElaineWu66** [JackZeng0208/llama.cpp-android-tutorial#4]
follow tutorial到clinfo -l均能正常显示：
Platform #0: QUALCOMM Snapdragon(TM)
 `-- Device #0: QUALCOMM Adreno(TM)

执行下一步cd bin/,  ./main 时显示Permission denied
返回llama.cpp目录 find . 也找不到main文件
尝试重新cmake依然不行
请问可能是什么原因呢？

**Comment by JackZeng0208** [comment]
你输chmod +x ./main看看呢，我之前也没遇到过这种情况

**Comment by ElaineWu66** [comment]
> 你输chmod +x ./main看看呢，我之前也没遇到过这种情况

尝试过了，也不行 显示：chmod: cannot access './main': No such file or directory

**Comment by ElaineWu66** [comment]
发现CMake的时候warning: Manually-specified variables were not used by the project: LLAMA_CLBLAST
会是这个原因么？
现在的CMakeLists.txt里已经找不到LLAMA_CLBLAST这个选项了，楼主方便share一下你参考的CMakeLists.txt么

**Comment by JackZeng0208** [comment]
不好意思，我的设备暂时不在身边，没办法导出CMakeLists。
然后这个教程是我去年写的，可能很多东西已经变了。我打算最近重写一下。
