### ISSUE TITLE
Can't build with CBlast fatal error: 'execinfo.h' file not found

### ISSUE THREAD

**Issue by agret** [JackZeng0208/llama.cpp-android-tutorial#5]
fatal error: 'execinfo.h' file not found

![Screenshot_2024-07-28-21-00-08-36_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/df4dea29-7c75-432f-a532-73aed5573b38)

**Comment by agret** [comment]
I have searched on Google and the problem is Android NDK does not have execinfo.h - this means that we can't build llama.cpp for Android :(

**Comment by JackZeng0208** [comment]
I will write a new tutorial and try to figure it out
